### ISSUE TITLE
why isnt this open source 

### ISSUE THREAD

**Issue by icymanred** [denq04/denq04.github.io#3]
why aint ncms open source i suspect it is a virus

**Comment by denq04** [comment]
It is not open source, because i want to keep my code private
Hundred of thousands people using it, its not a virus, and you can alway check it on https://virustotal.com
Also, NCMS is a c# assembly, so it can be decompiled using dnSpy or dotPeek, and you always can check what is inside
But if you still not sure, there is open source alternative named `NML`, you can find it by yourself

**Comment by icymanred** [comment]
> It is not open source, because i want to keep my code private Hundred of thousands people using it, its not a virus, and you can alway check it on https://virustotal.com Also, NCMS is a c# assembly, so it can be decompiled using dnSpy or dotPeek, and you always can check what is inside But if you still not sure, there is open source alternative named `NML`, you can find it by yourself

ok well im gona decompile it so everyone can see its open source hahahaha

**Comment by denq04** [comment]
You can't, because you have no permission for that

**Comment by icymanred** [comment]
whos gona stop me

**Comment by denq04** [comment]
Rules and common sense

**Comment by icymanred** [comment]
thats not gona stop me from uploading ur code lol
